[workspace]
members = [
    "interpreter",
    "parser",
    "scanner",
    "main",
    "common",
    "macros",
]
resolver = "2"

[workspace.dependencies]
peekmore = "1.3.0"
thiserror = "1.0"
ariadne = { git = "https://github.com/gabrielbrunop/ariadne.git", branch = "main" }