[workspace]
members = ["crates/*", "tests"]
resolver = "2"

[workspace.dependencies]
peekmore = "1.3.0"
thiserror = "1.0"
chrono = "0.4.40"
indexmap = "1.7.0"

[workspace.package]
version = "1.0.0-alpha.1"
authors = ["Gabriel Bruno Oliveira Pereira <gabrielbrunop@gmail.com>"]
