[package]
name = "tenda-playground"
version.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
tenda-core = { path = "../core" }
tenda-playground-platform = { path = "../tenda-playground-platform" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
