[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
macros = { path = "../macros" }
thiserror = { workspace = true }
ariadne = { workspace = true }