[package]
name = "tenda-prelude"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"

[dependencies]
tenda-runtime = { workspace = true }
indexmap = { workspace = true }
