[package]
name = "tenda-prelude"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Prelude for the Tenda programming language"
edition = "2021"

[dependencies]
tenda-runtime = { workspace = true }
indexmap = { workspace = true }
