[package]
name = "tenda-core"
version = "0.1.0"
edition = "2021"

[dependencies]
runtime = { path = "../runtime" }
parser = { path = "../parser" }
scanner = { path = "../scanner" }
common = { path = "../common" }
