[package]
name = "tenda"
version.workspace = true
authors.workspace = true
edition = "2021"
default-run = "tenda"

[dependencies]
tenda-core = { path = "../core" }
reedline = "0.39.0"
yansi = "1.0"
clap = { version = "4.5", features = ["derive"] }
