[package]
name = "tenda-playground-platform"
version.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
tenda-runtime = { path = "../runtime" }
tenda-os-platform = { path = "../os-platform" }
delegate = "0.13.3"
