[package]
name = "tenda-playground-platform"
version = "0.0.0"  
authors.workspace = true
publish = false
edition = "2021"

[dependencies]
tenda-runtime = { path = "../runtime" }
tenda-os-platform = { path = "../os-platform" }
delegate = "0.13.3"
