[package]
name = "tenda-reporting"
version.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
thiserror = { workspace = true }
ariadne = { git = "https://github.com/gabrielbrunop/ariadne.git", branch = "main" }
