[package]
name = "tenda-reporting"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Reporting utilities for the Tenda programming language"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
aegean = "0.6.0"
