[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
scanner = { path = "../scanner" }
common = { path = "../common" }
macros = { path = "../macros" }
thiserror = { workspace = true }
peekmore = { workspace = true }
ariadne = { workspace = true }