[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
scanner = { path = "../scanner" }
thiserror = { workspace = true }
peekmore = { workspace = true }
miette = { workspace = true }