[package]
name = "tenda-common"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"

[dependencies]
tenda-reporting = { path = "../reporting" }
thiserror = { workspace = true }
