[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
scanner = { path = "../scanner" }
thiserror = { workspace = true }
miette = { workspace = true }
indexmap = "1.7.0"
chrono = "0.4.40"
chrono-tz = "0.10.1"