[package]
name = "tenda-os-platform"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"

[dependencies]
tenda-runtime = { path = "../runtime" }
chrono = { workspace = true }
rand = "0.9.0"
