[package]
name = "tenda-scanner"
version.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
tenda-common = { path = "../common" }
tenda-reporting-derive = { path = "../reporting-derive" }
tenda-reporting = { path = "../reporting" }
thiserror = { workspace = true }
